App\Entity\Lesson:
    type: entity
    repositoryClass: App\Repository\LessonRepository
    table: lessons
    indexes:
        - { columns: [created_at] }
        - { columns: [name] }
    id: { id: { type: uuid } }
    fields:
        createdAt: { type: datetime }
        name: { type: string, length: 255 }
        description: { type: string, length: 1000 }
    manyToOne:
        course:
            targetEntity: App\Entity\Course
            joinColumn: { nullable: false }
